spring:
  application:
    name: rabbitmq-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
